name: Deploy static site to S3 + CloudFront
on:
  push:
    branches: [ main ]
    # only run when website files change:
    paths:
      - 'site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      S3_BUCKET: portfolio-jaden
      CLOUDFRONT_DISTRIBUTION_ID: EJO8JZXNMBOQC
      AWS_REGION: us-east-2

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync site to S3
        run: |
          aws s3 sync site s3://$S3_BUCKET --delete --region $AWS_REGION

      - name: Set no-cache on resume.pdf (optional)
        if: ${{ hashFiles('site/resume.pdf') != '' }}
        run: |
          if [ -f site/resume.pdf ]; then
            aws s3 cp site/resume.pdf s3://$S3_BUCKET/resume.pdf \
              --region $AWS_REGION \
              --content-type application/pdf \
              --cache-control "no-cache, no-store, must-revalidate" \
              --metadata-directive REPLACE
          fi

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
